[package]
name = "tube_transporter"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"


[dependencies]
base = { path = "../base" }
rand = "0.8"
thiserror = "1.0.20"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"

[target.'cfg(windows)'.dependencies]
win_util = { path = "../win_util"}
winapi = "*"
