[package]
name = "audio_streams"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
path = "src/audio_streams.rs"

[dependencies]
async-trait = "0.1.36"
remain = "0.2"
thiserror = "1.0.20"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
