[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
[build]
target = "x86_64-naked.json"
[target.x86_64-naked]
rustflags = [
  "-C", "link-arg=-Tlayout.ld",
]
#Example for running with debugging
#runner = "crosvm run --disable-sandbox --gdb 7777"
runner = "crosvm run --disable-sandbox"
