[package]
name = "serde_keyvalue"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
argh_derive = ["argh", "serde_keyvalue_derive"]

[dependencies]
argh = { version = "0.1.7", optional = true }
serde_keyvalue_derive = { path = "serde_keyvalue_derive", optional = true } # provided by ebuild
serde = "1"
thiserror = { version = "1.0.20" }
remain = "*"
num-traits = "0.2"
nom = { version = "7.1.0", features = ["alloc"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
