[package]
name = "protos"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
composite-disk = []
plugin = ["kvm_sys"]
registered_events = []

[dependencies]
kvm_sys = { path = "../kvm_sys", optional = true }
protobuf = "3.2"

[build-dependencies]
proto_build_tools = { path = "../proto_build_tools" }
