[package]
name = "power_monitor"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
powerd = ["dbus"]

[dependencies]
base = { path = "../base" }
dbus = { version = "0.9", optional = true }
protobuf = "3.2"
remain = "0.2"
thiserror = "1.0.20"

[build-dependencies]
proto_build_tools = { path = "../proto_build_tools" }
