[package]
name = "resources"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
libc = "*"
base = { path = "../base" }
serde = { version = "1", features = ["derive"] }
remain = "*"
thiserror = "*"
