name: Build and Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/crosvm-infra/crosvm_dev:latest
    strategy:
      matrix:
        rust:
          - "1.75.0"
          - "1.76.0"
          - "1.77.0"
          - "stable" # stable is 1.77.1
          - "beta" # beta
          # - "nightly" # nightly
        crate:
          - "jetstream"
          - "jetbridge"
          - "libcrosvm"
          - "bldy"
          - "innitguv"
    steps:
      - uses: actions/checkout@v3
       # use crate as the working directory
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl cmake clang       
      - name: Change working directory
        run: |
          cd ${{ matrix.crate }}         
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup default ${{ matrix.rust }}
          rustup install ${{ matrix.rust }}
          echo ${{ matrix.rust }} > rust-toolchain
      - name: Build ${{ matrix.rust }}      
        run: |
          cd ${{ matrix.crate }}
          RUST_TOOLCHAIN=${{ matrix.rust }} cargo build --verbose
      - name: Run tests
        run: |
          cd ${{ matrix.crate }}
          RUST_TOOLCHAIN=${{ matrix.rust }} cargo test --verbose